import React from 'react'
import Head from 'next/head'
import Footer from './footer'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'
import { parse } from 'path'
import { useState } from 'react'
import Fade from 'react-reveal/Fade';
import Hero from './hero'
// import { getServerSideProps } from './blogpost/[slug]'
import * as fs from 'fs';
const Home = (props) => {
  const [blogs, setBlogs] = useState(props.allBlogs)

  return (
    <>
      <style jsx>
        {`
      .popularHeader {
      display: flex;
      justify-content: center;
      padding: 10px;
      font-size:25px;
      }
    `}
      </style>
      <Head>
        <title>Next Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className={styles.main}>
        {/* blogs  */}
        <div className={styles.blogs}>
          <h1 className={styles.popularHeader}>Popular Blogs</h1>
          <Fade bottom>
            {blogs.map((blogItem) => {
              return <div key={blogItem.title} className={styles.blogItem}>
                <Link href={`/blogpost/${blogItem.slug}`}>
                  <h3>{blogItem.title}</h3>
                </Link>
                <p>{blogItem.metadesc.substr(0, 140)}....Read More</p>
              </div>
            })}
          </Fade>
        </div>
      </main>
      <Footer/>
    </>
  )
}
export async function getStaticProps(context) {
  let data = await fs.promises.readdir("blogdata");
  let myfile;
  let allBlogs = [];
  for (let index = 0; index < data.length; index++) {
    const item = data[index];
    myfile = await fs.promises.readFile(('blogdata/' + item), 'utf-8')
    allBlogs.push(JSON.parse(myfile))
  }

  return {
    props: { allBlogs }, // will be passed to the page component as props
  }
}
export default Home


// git push -u origin main