import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>
        {`
      .popularHeader {
      display: flex;
      justify-content: center;
      padding: 10px;
      font-size:25px;
      }
    `}
      </style>
      <Head>
        <title>Next Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* header  */}
        <div>
          <h1 className={styles.headerText}>Next Hunt</h1>
          <p className={styles.description}>
            A blog written by Next Hunter for other blog hunters
          </p>
        </div>
        {/* blogs */}
        <div className={styles.blogs}>
          <h2 className="popularHeader">Populer Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a scripting language that allows you to implement complex features on web pages</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a scripting language that allows you to implement complex features on web pages</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a scripting language that allows you to implement complex features on web pages</p>
          </div>
        </div>


      </main>
    </>
  )
}
